### ISSUE TITLE
TypeSchema breaks Next.js Turbopack dev server and edge deployment

### ISSUE THREAD

**Issue by TheEdoRan** [decs/typeschema#28]
Hi, I'm using TypeSchema in [next-safe-action](https://github.com/TheEdoRan/next-safe-action), which is a Next.js type safe wrapper for React Sever Actions.

Some users found out that since version 6 of the library, Next.js dev server using Turbopack (`next dev --turbo`) and deployments on Vercel using edge runtime are broken, due to TypeSchema internal errors. Additional information about these errors can be found [in this issue](https://github.com/TheEdoRan/next-safe-action/issues/49).

I'm not sure if these problems can be fixed easily, but I'm happy to help in any way I can. Thank you!

**Comment by sexnine** [comment]
I had similar issues with building for Cloudflare workers (which is actually what Vercel edge functions are built on top of).

The first issue I was having was building with esbuild, which would fail when bundling due to those packages not being installed.  I attempted to fix this by externalizing all the dependencies I wasn't using.  This made the build pass, but attempting to deploy to Cloudflare, there were still issues.

I then wrapped each import of the libraries with a try catch block that returns nothing when the import fails.  This has worked for me and hasn't caused me any issues so far.

Eg:
```diff
@@ -35,11 +35,13 @@ function isJSONSchema(schema) {
 
 // src/adapters/ajv.ts
 var fetchModule = /* @__PURE__ */ memoize(async () => {
+  try {
   const { default: Ajv } = await import(
     /* webpackIgnore: true */
     "ajv"
   );
   return new Ajv();
+  } catch {}
 });
 var coerce = /* @__NO_SIDE_EFFECTS__ */ (fn) => (schema) => isJSONSchema(schema) ? fn(schema) : void 0;
 var createValidate = /* @__PURE__ */ coerce(async (schema) => {
 ```
You can see the full patch [here](https://gist.github.com/sexnine/86e11e1ee4af4b90f49a3d87c6be8482) and see if that helps resolve your issue.

@decs Would you be open to a PR that implements these changes that should hopefully fix builds for certain tools?

**Comment by juliusmarminge** [comment]
Maybe just adding entrypoints for each adapter would be an option?

I'd be fine with importing from `@decs/typeschema/valibot`

**Comment by sexnine** [comment]
I think that would be a good idea.  Or possibly a function that allows the user to manually specify the adapters they want to support would be a good option.  And in that case, it might also be good for the user to pass the functions needed instead of typeschema importing them itself, for extra flexibility.

I'm happy to write a PR for this if you'd like.

**Comment by decs** [comment]
Thanks all for the discussion and pointers!

@sexnine's suggestion worked, so I decided to go with that approach (try/catch). `v0.12.2` was just published and includes Turbopack support.

> Relying on every bundler supporting these directives is just begging for issues and I'd say near impossible to support all runtimes / bundlers with a single entrypoint

Indeed it's being a challenge to rely on dynamic imports, but I truly believe that using optional peer deps is the best approach for solving this problem. Even if we have to whack-a-mole some bundlers. By having a single entrypoint, we can abstract TypeSchema away to the end developer. It just magically works.
